function addathletes() {
  //define a variable for the collection you want to create in Firestore to populate data
  var athleteRef = db.collection("athletes");
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1168148.jpg",
    noc: "DEN",
    code: "1168148",
    FamilyName: "Aagaard",
    lnk: "../../../en/results/ice-hockey/athlete-profile-n1168148-mikkel-aagaard.htm",
    GivenName: "Mikkel",
    Gender: "M",
    dis: "IHO",
    discNOrder: "",
    name: "AAGAARD Mikkel",
    orgNOrder: "",
    IFId: "",
    shortName: "AAGAARD M",
    event: "",
    BirthDate: "1995-10-18",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1005520.jpg",
    noc: "FIN",
    code: "1005520",
    FamilyName: "Aalto",
    lnk: "../../../en/results/ski-jumping/athlete-profile-n1005520-antti-aalto.htm",
    GivenName: "Antti",
    Gender: "M",
    dis: "SJP",
    discNOrder: "",
    name: "AALTO Antti",
    orgNOrder: "",
    IFId: "6996",
    shortName: "AALTO A",
    event: "",
    BirthDate: "1995-04-02",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1025177.jpg",
    noc: "FIN",
    code: "1025177",
    FamilyName: "Aaltonen",
    lnk: "../../../en/results/ice-hockey/athlete-profile-n1025177-miro-aaltonen.htm",
    GivenName: "Miro",
    Gender: "M",
    dis: "IHO",
    discNOrder: "",
    name: "AALTONEN Miro",
    orgNOrder: "",
    IFId: "",
    shortName: "AALTONEN M",
    event: "",
    BirthDate: "1993-06-07",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1192599.jpg",
    noc: "USA",
    code: "1192599",
    FamilyName: "Abdelkader",
    lnk: "../../../en/results/ice-hockey/athlete-profile-n1192599-justin-abdelkader.htm",
    GivenName: "Justin",
    Gender: "M",
    dis: "IHO",
    discNOrder: "",
    name: "ABDELKADER Justin",
    orgNOrder: "",
    IFId: "",
    shortName: "ABDELKADER J",
    event: "",
    BirthDate: "1987-02-25",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1051423.jpg",
    noc: "KSA",
    code: "1051423",
    FamilyName: "ABDI",
    lnk: "../../../en/results/alpine-skiing/athlete-profile-n1051423-fayik-abdi.htm",
    GivenName: "Fayik",
    Gender: "M",
    dis: "ALP",
    discNOrder: "",
    name: "ABDI Fayik",
    orgNOrder: "",
    IFId: "962401",
    shortName: "ABDI F",
    event: "",
    BirthDate: "1997-10-07",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1041502.jpg",
    noc: "USA",
    code: "1041502",
    FamilyName: "Abdul-Saboor",
    lnk: "../../../en/results/bobsleigh/athlete-profile-n1041502-hakeem-abdul-saboor.htm",
    GivenName: "Hakeem",
    Gender: "M",
    dis: "BOB",
    discNOrder: "",
    name: "ABDUL-SABOOR Hakeem",
    orgNOrder: "",
    IFId: "263612",
    shortName: "ABDUL-SABOOR H",
    event: "",
    BirthDate: "1987-11-07",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1052177.jpg",
    noc: "ERI",
    code: "1052177",
    FamilyName: "Abeda",
    lnk: "../../../en/results/alpine-skiing/athlete-profile-n1052177-shannon-abeda.htm",
    GivenName: "Shannon",
    Gender: "M",
    dis: "ALP",
    discNOrder: "",
    name: "ABEDA Shannon",
    orgNOrder: "",
    IFId: "959600",
    shortName: "ABEDA S",
    event: "",
    BirthDate: "1996-05-15",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1095706.jpg",
    noc: "GER",
    code: "1095706",
    FamilyName: "Abeltshauser",
    lnk: "../../../en/results/ice-hockey/athlete-profile-n1095706-konrad-abeltshauser.htm",
    GivenName: "Konrad",
    Gender: "M",
    dis: "IHO",
    discNOrder: "",
    name: "ABELTSHAUSER Konrad",
    orgNOrder: "",
    IFId: "",
    shortName: "ABELTSHAUSER K",
    event: "",
    BirthDate: "1992-09-02",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1037253.jpg",
    noc: "LAT",
    code: "1037253",
    FamilyName: "Abols",
    lnk: "../../../en/results/ice-hockey/athlete-profile-n1037253-rodrigo-abols.htm",
    GivenName: "Rodrigo",
    Gender: "M",
    dis: "IHO",
    discNOrder: "",
    name: "ABOLS Rodrigo",
    orgNOrder: "",
    IFId: "",
    shortName: "ABOLS R",
    event: "",
    BirthDate: "1996-01-05",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1042098.jpg",
    noc: "UKR",
    code: "1042098",
    FamilyName: "Abramenko",
    lnk: "../../../en/results/freestyle-skiing/athlete-profile-n1042098-oleksandr-abramenko.htm",
    GivenName: "Oleksandr",
    Gender: "M",
    dis: "FRS",
    discNOrder: "",
    name: "ABRAMENKO Oleksandr",
    orgNOrder: "",
    IFId: "2472951",
    shortName: "ABRAMENKO O",
    event: "",
    BirthDate: "1988-05-04",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1182014.jpg",
    noc: "USA",
    code: "1182014",
    FamilyName: "Abruzzese",
    lnk: "../../../en/results/ice-hockey/athlete-profile-n1182014-nick-abruzzese.htm",
    GivenName: "Nick",
    Gender: "M",
    dis: "IHO",
    discNOrder: "",
    name: "ABRUZZESE Nick",
    orgNOrder: "",
    IFId: "",
    shortName: "ABRUZZESE N",
    event: "",
    BirthDate: "1999-06-04",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1055931.jpg",
    noc: "NED",
    code: "1055931",
    FamilyName: "Achtereekte",
    lnk: "../../../en/results/speed-skating/athlete-profile-n1055931-carlijn-achtereekte.htm",
    GivenName: "Carlijn",
    Gender: "F",
    dis: "SSK",
    discNOrder: "",
    name: "ACHTEREEKTE Carlijn",
    orgNOrder: "",
    IFId: "SSNED22901199001",
    shortName: "ACHTEREEKTE C",
    event: "",
    BirthDate: "1990-01-29",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1058380.jpg",
    noc: "CHN",
    code: "1058380",
    FamilyName: "Adake",
    lnk: "../../../en/results/speed-skating/athlete-profile-n1058380-ahenaer-adake.htm",
    GivenName: "Ahenaer",
    Gender: "F",
    dis: "SSK",
    discNOrder: "",
    name: "ADAKE Ahenaer",
    orgNOrder: "",
    IFId: "SSCHN20106199901",
    shortName: "ADAKE A",
    event: "",
    BirthDate: "1999-06-01",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1035826.jpg",
    noc: "FRA",
    code: "1035826",
    FamilyName: "Adelisse",
    lnk: "../../../en/results/freestyle-skiing/athlete-profile-n1035826-antoine-adelisse.htm",
    GivenName: "Antoine",
    Gender: "M",
    dis: "FRS",
    discNOrder: "",
    name: "ADELISSE Antoine",
    orgNOrder: "",
    IFId: "2528623",
    shortName: "ADELISSE A",
    event: "",
    BirthDate: "1996-06-10",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1041974.jpg",
    noc: "SWE",
    code: "1041974",
    FamilyName: "Adolfsson",
    lnk: "../../../en/results/ice-hockey/athlete-profile-n1041974-jessica-adolfsson.htm",
    GivenName: "Jessica",
    Gender: "F",
    dis: "IHO",
    discNOrder: "",
    name: "ADOLFSSON Jessica",
    orgNOrder: "",
    IFId: "",
    shortName: "ADOLFSSON J",
    event: "",
    BirthDate: "1998-07-15",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1048257.jpg",
    noc: "SUI",
    code: "1048257",
    FamilyName: "Aerni",
    lnk: "../../../en/results/alpine-skiing/athlete-profile-n1048257-luca-aerni.htm",
    GivenName: "Luca",
    Gender: "M",
    dis: "ALP",
    discNOrder: "",
    name: "AERNI Luca",
    orgNOrder: "",
    IFId: "511983",
    shortName: "AERNI L",
    event: "",
    BirthDate: "1993-03-27",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1045273.jpg",
    noc: "BEL",
    code: "1045273",
    FamilyName: "Aerts",
    lnk: "../../../en/results/bobsleigh/athlete-profile-n1045273-sara-aerts.htm",
    GivenName: "Sara",
    Gender: "F",
    dis: "BOB",
    discNOrder: "",
    name: "AERTS Sara",
    orgNOrder: "",
    IFId: "263957",
    shortName: "AERTS S",
    event: "",
    BirthDate: "1984-01-25",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1166960.jpg",
    noc: "SUI",
    code: "1166960",
    FamilyName: "Aeschlimann",
    lnk: "../../../en/results/ice-hockey/athlete-profile-n1166960-sandro-aeschlimann.htm",
    GivenName: "Sandro",
    Gender: "M",
    dis: "IHO",
    discNOrder: "",
    name: "AESCHLIMANN Sandro",
    orgNOrder: "",
    IFId: "",
    shortName: "AESCHLIMANN S",
    event: "",
    BirthDate: "1994-12-26",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1182000.jpg",
    noc: "USA",
    code: "1182000",
    FamilyName: "Agostino",
    lnk: "../../../en/results/ice-hockey/athlete-profile-n1182000-kenny-agostino.htm",
    GivenName: "Kenny",
    Gender: "M",
    dis: "IHO",
    discNOrder: "",
    name: "AGOSTINO Kenny",
    orgNOrder: "",
    IFId: "",
    shortName: "AGOSTINO K",
    event: "",
    BirthDate: "1992-04-30",
  });
  athleteRef.add({
    img: "../../../static/owg2022/img/bios/photos/thumb/1001848.jpg",
    noc: "IRI",
    code: "1001848",
    FamilyName: "Ahmadi",
    lnk: "../../../en/results/alpine-skiing/athlete-profile-n1001848-atefeh-ahmadi.htm",
    GivenName: "Atefeh",
    Gender: "F",
    dis: "ALP",
    discNOrder: "",
    name: "AHMADI Atefeh",
    orgNOrder: "",
    IFId: "265053",
    shortName: "AHMADI A",
    event: "",
    BirthDate: "2000-12-23",
  });
}
